# Generated by Django 2.2.24 on 2022-06-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='healthdepts',
        ),
    ]
